### PR TITLE
Relocate interrupt vectors to SRAM

### PR DESCRIPTION
**Pull request by heimir-sverrisson**
Addresses of interrupt service routines are now stored in top of SRAM to allow programs loaded by the bootloader to override them. See TI Application Note in `docs/spna236.pdf`.

### CODE REVIEW

**Comment by burnsfisher** [comment]
I had missed that there are some vectors that have "hard coded" addresses, as opposed to the VIM.  I understand.  But what I don't really understand is why the loaded program vectors can't be in flash as opposed to SRAM.  In fact, if they were at the bottom of the flash for the loaded program (i.e. just above the loader flash) would that allow a branch directly from the 0-based vector?  It appears to me that the Application Note says SRAM mainly to allow the vectors to be changed among multiple programs, an issue which we do not have.
It is probably not especially critical, except that it would be nice just to relocate the application code (including the vectors created by HALCoGen) using the linker.  

Any thoughts?

**Comment by heimir-sverrisson** [comment]
I think we can use the flexibility of this method.

When we install the Flashloader for the first time there is no application above it in the flash so we cannot have an unconditional branch to an Exception handler outside of the Flashloader itself at that point. Adding logic into the Flashloader to handle that is cumbersome at best.

Trying to update the low memory when we load the application would be really tricky as we must flash one page at a time.

The symbols used in this method are all generated by HalCoGen and the linker, so once this modification has been done once per project, we can go as many HalCoGen cycles as we need during development without worries. Also I've verified that just by stopping the CCS from wiping out all flash (the default) when JTAGging running and debugging the application in CCS works just fine after it has been relocated to 0x00010100.

I also think it is useful to be able to run multiple applications above the Flashloader, in addition to the regular Flight Software, i.e. something that runs hardware exercise tests etc.

**Comment by burnsfisher** [comment]
Ok, I see, and you make good points.  I'm still hung up on the STM32 where you always put the vectors in flash and then just write their address into a register.  I want to check a couple things and then I will get back one more time.

**Comment by burnsfisher** [comment]
A couple things.  First, why are there two repos, one flashloader and one flashloader-ti?  The -ti one has not been updated for a couple weeks.  Should that be deleted?  That said, having ti is not a bad idea.  Then I could put the STM32 version here too (after I figure out the copyleft ethics---I've made changes, but I'm pretty sure that the original authors placed it under one of the GPL licenses.  I'll put the second comment separately.

**Comment by burnsfisher** [comment]
Ok, I had to look at the code more to see whether what I was about to say was silly :-)  But then I think I found another issue in the process.  What I was going to say was that the STM32 code just used the "code is ok" pattern to decide whether to use the loader vector address or the application vector address (in the STM32 you put the address in a register).  But that got me off on another issue:

It appears to me that the "override" that you put in so that we do or do not go into the loader regardless of the state of the GPIO "attached" line is in flash.   And it also appears that if the GPIO attached line is high, it will ALWAYS enter the loader regardless of the state of the pattern.  Let me see if I can do a truth table for what I intended and try to explain the usefulness of it.  (The 3 columns are the state of the magic number.  The two rows are the state of the GPIO.  The internal values are what each pair of values means.

                            Pattern = random                  Pattern = loader                     Pattern = Application
GPIO high              Go to loader                           Go to loader                          Go to application
GPIO low                Go to application                    Go to loader                         Go to application

The STM32 loader had 2 "magic values" and a pattern.  If the magic numbers were exactly right, then pay attention to the pattern.  Otherwise consider the pattern random in the table above.  Random was intended to mean that there was a power cycle, so the SRAM might be anything (but are probably 0). In which case only trust the GPIO value.

The two non-random values of the pattern  were for use during debugging.  When debugging/testing, there is often a USB/serial connection attached, so the GPIO line is high.  

But often we do not want to hit the loader every time the processor resets.  This may be because we are using a debugger, or because we want a different program connected to the serial line or whatever.  (This is more important for a USB loader, by the way, but better to have them consistent).   In this case, the application writes the magic numbers and then the pattern to re-run the application and then resets the processor.  The loader gets (mostly) skipped.  

Alternatively we have had occasions where the GPIO connection was not working correctly,  (or in the case of UMaine they forgot to connect it!) and we wanted a way to force the loader to run even if the 'attached' connection was low.  In that case, set the magic numbers and the pattern to "loader" and reset.  

And of course the reason to put this in SRAM is so that the application can write these values easily.

--------------------------------------------
I'd also like to suggest that these values as well as the interrupt vectors be in the BOTTOM of sram rather than the top.  Then it would work with ease in several different processor variants with different amounts of memory.  In this case, both the loader and the application would have to hard-code the addresses of these variables in the linker.

What do you think?

**Comment by heimir-sverrisson** [comment]
@burnsfisher This scheme makes perfect sense to me. I will merge and close this PR and then implement this scheme in a new PR.
Thank you!

**Pull request merged**
